global:
  certStoragePath: ./cert_storage
providers:
  - providerName: aliDNS  # DNS提供商名称，支持aliDNS|tencentCloud
    enable: true        # 是否启用该证书托管,默认为true启用
    domains: # 只能写一个子域，多个域名复制多个ProviderName选项，例外： *.xx.com和二级主域可以同时颁发
      - "itgod.orm"   # 设置通配付域名的ssl
      - "*.itgod.com"
    saveSSLName:         # 默认留空，指定SSL证书保存的名字，留空则默认使用domains[0].key的名称
    renewBeforeDay: 10  # 到期前10天重新颁发
    email: "your@mail.com" # 申请证书时设置的邮箱
    hook: "" # 默认留空, 填写脚本路径后，颁发完证书会主动调用外部脚本
    accessKey: "xxx"   # alidns有key 或 腾讯云的secret_id
    secretKey: "xxx"   # alidns的secret 或 腾讯云的secre_key

  # 以下是第二个需要托管的域名配置
  - providerName: tencentCloud   # DNS提供商名称，支持aliDNS|tencentCloud
    enable: false
    domains:
      - "home.itgod.org"
    saveSSLName:         # 默认留空
    renewBeforeDay: 10  # 到期前10天重新颁发
    email: "your@mail.com" # 申请证书时设置的邮箱
    hook: "ifconfig" # 默认留空, 填写脚本路径或命令后，颁发完证书会主动调用外部命令或脚本
    accessKey: "xxx"
    secretKey: "xxx"
