global:
  certStoragePath: ./cert_storage
providers:
  - providerName: aliDNS  # DNS提供商名称，支持aliDNS|dnsPod
    enable: true        # 是否启用该证书托管,默认为true启用
    domains: # 只能写一个子域，例外： *.xx.com和二级主域可以同时颁发
      - "buydance.com"   # 设置通配付域名的ssl
      - "*.buydance.com"
    saveSSLName:         # 默认留空，指定SSL证书保存的名字，留空则默认使用domains[0].key的名称
    renewBeforeDay: 10  # 到期前10天重新颁发
    email: "your@mail.com" # 申请证书时设置的邮箱
    hook: "" # 默认留空, 填写脚本路径后，颁发完证书会主动调用外部脚本
    accessKey: "xxx"   # alidns有key和secret，dnspod只需要access token
    secretKey: "xxx"
    # DNS POD配置样本
  - providerName: dnsPod
    enable: true        # 是否启用该证书托管,默认为true启用
    domains: # 只能写一个子域，例外： *.xx.com和二级主域可以同时颁发
      - "itgod.org"
      - "*.itgod.org"
    saveSSLName:         # 默认留空，指定SSL证书保存的名字，留空则默认使用domains[0].key的名称
    renewBeforeDay: 10  # 到期前10天重新颁发
    email: "your@mail.com" # 申请证书时设置的邮箱
    hook: "ipconfig" # 默认留空, 填写脚本路径后，颁发完证书会主动调用外部脚本
    accessKey: "5089,you token"  # 填写dnspod token, 格式APPID,TOKEN
    secretKey: ""
